server:
  port: 3000

facebook:
  page:
    id: ${PAGE_ID}
    access-token: ${PAGE_ACCESS_TOKEN}
  graph:
    api:
      url: https//graph.facebook.com/v19.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BlogAI
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false