server:
  port: 8080

facebook:
  page:
    id: YOUR_PAGE_ID
    access-token: YOUR_PAGE_ACCESS_TOKEN
  graph:
    api:
      url: https://graph.facebook.com/v19.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
